version: "{branch} {build}"

build:
  verbosity: detailed

install:
  - choco install gradle --version 4.2.1

before_build:
  - ps: Get-Command java

build_script:
  - gradle assemble --no-daemon

test_script:
  - gradle check --no-daemon

after_test:
  - ps: |
        $wc = New-Object 'System.Net.WebClient'
        Get-ChildItem . -Name -Recurse 'TEST-*.xml'  |
        Foreach-Object {
            $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $_))
        }
  - gradle bundledJar --no-daemon
  - mv build/libs/alpha-bundled.jar alpha.jar

artifacts:
  path: alpha.jar

environment:
  matrix:
  - platform: x64
    #    JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  - platform: x86
    #JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0

cache:
  - C:\Users\appveyor\.gradle
