# Route our builds to Travis CI's Container Based
# Infrastructure for shorter queue times.
# https://docs.travis-ci.com/user/workers/container-based-infrastructure/#Routing-your-build-to-container-based-infrastructure
sudo: true

language: java

# We test against Java releases:
#  - greater than 7
#  AND
#    - with LTS and in "Premier Support" phase
#    OR
#    - not succeeded by any other release
# https://www.oracle.com/technetwork/java/java-se-support-roadmap.html
# https://docs.travis-ci.com/user/languages/java#Testing-Against-Multiple-JDKs
jdk:
  # LTS and in "Premier Support" as of 2019-03 (until 2022-03)
  - openjdk8
  # - oraclejdk8 # Removed due to not being supported on Ubuntu xenial
  # LTS and in "Premier Support" as of 2019-03 (until 2023-09)
  - openjdk11
  - oraclejdk11
  # Not succeeded as of 2019-03. Scheduled to be succeeded by
  # Java 13 in 2019-09, see http://openjdk.java.net/projects/jdk/13/spec/
  - openjdk12
  # No Oracle JDK >11, see
  # https://blogs.oracle.com/java-platform-group/oracle-jdk-releases-for-java-11-and-later

# As of 2016-06 Travis CI is running an outdated
# version of Gradle, so this workaround fetches
# a given version before carrying out the build.
before_install:
  # Setup Gradle configuration, tell it not to spawn a daemon.
  # Gradle will complain and ask us to enable the daemon, but
  # disabling it actually is a good practice for CI. Docs at
  # https://docs.gradle.org/4.1/userguide/gradle_daemon.html#when_should_i_not_use_the_gradle_daemon
  - mkdir -pv $HOME/.gradle
  - echo 'org.gradle.daemon=false' > $HOME/.gradle/gradle.properties

  # Set memory limits for Gradle and Java processes it spawns.
  - export GRADLE_OPTS="-Xmx1g -Xss8m"
  - echo 'org.gradle.jvmargs=-Xmx1g' >> $HOME/.gradle/gradle.properties

install:
  - true

script:
  - ./gradlew build --scan --stacktrace

after_success:
  - ./gradlew jacocoTestReport coveralls
  - bash <(curl -s https://codecov.io/bash)

# Do not send notifications via e-mail, this gets
# annoying pretty fast. Check Travis CI docs at
# https://docs.travis-ci.com/user/notifications/#Email-notifications
notifications:
  email: false

# before_cache and after_cache to leverage caching
# of dependencies according to Travis CI docs, see
# https://docs.travis-ci.com/user/languages/java#Caching
# Also according to Gradle docs, see
# https://guides.gradle.org/executing-gradle-builds-on-travisci/#enable_caching_of_downloaded_artifacts
before_cache:
  - rm -fv  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fvr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
