version: "{branch} {build}"

build:
  verbosity: detailed

install:
  - choco install gradle --version 4.2.1

build_script:
  - gradle assemble --no-daemon

test_script:
  - gradle check --no-daemon

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0

cache:
  - C:\Users\appveyor\.gradle
