name: ci

on: [push]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      os: [ubuntu-latest, windows-latest, macos-latest]
      java: [8, 11, 13]
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - run: ./gradlew build
